---

- name: "Add Node.js" 
  become: true
  shell:
    curl -fsSL https://deb.nodesource.com/setup_13.x | sudo -E bash -

- name: "Install Node.js 13"
  become: true
  shell:
    sudo apt-get install -y nodejs

- name: "Install PM Global"
  npm:
    name: PM2
    global: yes
