---

- name: "Backend DIR" 
  file:
    path: ~/backed_application
    state: directory

- name: "Copy artifact to backend app"
  copy:
    src: artifact.tar.gz
    dest: ~/backed_application
    remote_src: yes

- name: "unarchive files" 
  unarchive:
    src: artifact.tar.gz
    dest: ~/backed_application
    remote_src: yes
    

- name: "Install dependencies" 
  shell: |
    cd ~/backed_application
    npm i

- name: "PM2 excussion"
  shell: |
    cd ~/backed_application/dist
    pm2 stop default
    pm2 start main.js