---

- name: "Backend DIR" 
  file:
    path: ~/backed_application
    state: directory

- name: "copy backend binaries"
  become: true
  synchronize:
    src: ../../backend/dist
    dest: ~/backed_application
    recursive: true
  
- name: "copy node_modules"
  become: true
  synchronize:
    src: ../../backend/node_modules
    dest: ~/backed_application
    recursive: true

- name: "copy package"
  become: true
  synchronize:
    src: ../../backend/package*
    dest: ~/backed_application
    recursive: true
    
- name: "Install dependencies" 
  shell: |
    cd ~/backed_application
    npm i

- name: "PM2 excussion"
  shell: |
    cd ~/backed_application/dist
    pm2 stop default
    pm2 start main.js