---
  - name: "Backend DIR" 
    file:
      path: ~/backed_application
      state: directory

  - name: "unarchive files"
    unarchive:
      src: artifact.tar.gz
      dest: ~/backed_application

  - name: "Install dependencies" 
    shell: |
      cd ~/backed_application
      npm i

  - name: "PM2 excussion"
    shell: |
      cd ~/backed_application/dist
      pm2 stop default
      pm2 start main.js    
      
    environment:
      ENVIRONMENT: production
      TYPEORM_CONNECTION: "{{ lookup('env', 'TYPEORM_CONNECTION') }}"
      TYPEORM_MIGRATIONS_DIR: "./migrations"
      TYPEORM_MIGRATIONS: "./migrations/*.js"
      TYPEORM_ENTITIES: "./modules/domain/**/*.entity{.ts,.js}"
      TYPEORM_HOST: "{{ lookup('env', 'TYPEORM_HOST') }}"
      TYPEORM_PORT: "{{ lookup('env', 'TYPEORM_PORT') }}"
      TYPEORM_USERNAME: "{{ lookup('env', 'TYPEORM_USERNAME') }}"
      TYPEORM_PASSWORD: "{{ lookup('env', 'TYPEORM_PASSWORD') }}"
      TYPEORM_DATABASE: "{{ lookup('env', 'TYPEORM_DATABASE') }}"